server:
  port: 8082

spring:
  application:
    name: portfolio-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/portfolios
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: localhost:8080/realms/portfolios/protocol/openid-connect/certs
management:
  endpoints:
    web:
      exposure:
        include: "*"
